### ISSUE TITLE
Beteiligte NGOs aufführen

### ISSUE THREAD

**Issue by milafrerichs** [okfde/entwicklungsbarometer#15]
Unter den Visualisierungen auf der 2. Ebene die beteiligten NGOs aufführen.
### Sicherheit:
- [ ] BICC
- [ ] [Center for Global Development](http://www.cgdev.org)
- [ ] [Saferworld](http://www.saferworld.org)
- [ ] [Freedom House](http://www.freedomhouse.org)

**Comment by milafrerichs** [comment]
![bildschirmfoto 2014-08-01 um 13 09 21](https://cloud.githubusercontent.com/assets/688980/3778061/50953a38-196c-11e4-959a-ef21fae0f2a2.png)

**Comment by ClaudiaSchwegmann** [comment]
:+1:
