### ISSUE TITLE
CDI Ranking

### ISSUE THREAD

**Issue by milafrerichs** [okfde/entwicklungsbarometer#2]
Alle Länder darstellen. 
- [ ] CDI Overall ranking
  - [ ] Ranking der einzelnen Länder
  - [ ] Subrankings direkt integrieren
- [ ] CDI Sektor ranking

**Comment by milafrerichs** [comment]
Sollen auf der Übersichtsseite wie beim CDI die Unterscores auch aufgeführt werden? Oder nur der Gesamtscore?
![cdi visualisierung_rot](https://cloud.githubusercontent.com/assets/688980/3747739/77a8496c-17d2-11e4-9288-89acbe8aee3e.jpg)

**Comment by ClaudiaSchwegmann** [comment]
Hi Mila. Jetzt nutze ich GitHub :) . Zu dDeiner Frage in der email. Ja, genau, horizontal. Ich würde die gegenwärtige Reihenfolge auch beibehalten, damit man sofort sieht an welcher Stelle Deutschland steht. Man könnte Deutschland dann vielleicht farblich hervorheben. Außerdem wäre es gut, wenn man sofort sehen könnte, welche Seite entwicklungspolitisch gut ist und welche schlecht. In diesem Fall sind ja die Länder mit den höchsten Werten die schlechtesten. In anderen Fällen sind die Länder mit den höchsten Werten die besten. Da sollten wir alle Mißverständnisse ausschließen. 
Zu den Unterscores ... - am liebsten hätte ich die auch.

**Comment by ClaudiaSchwegmann** [comment]
Wenn ich es richtig sehe, wäre es am besten, wenn das Center for Global Development.ein API hätte, um die Daten automatisch einzulesen. Dann müsste man doch auch nicht alles "manuell" aktualisieren wenn im November die neuen CDI Daten kommen, richtig? Oder ist das eine falsche Annahme?

**Comment by milafrerichs** [comment]
@ClaudiaSchwegmann nein das siehst du richtig. Eine API wäre am besten, aber keine Ahnung ob die eine haben, ich würde vermuten, dass das nicht der Fall ist.

**Comment by milafrerichs** [comment]
Hier wäre eine erste Version @ClaudiaSchwegmann 
![bildschirmfoto 2014-07-30 um 15 01 01](https://cloud.githubusercontent.com/assets/688980/3749240/a3ccc3da-17e9-11e4-878a-42b0d95046ee.png)

**Comment by milafrerichs** [comment]
Jetzt auch nach Größe sortiert.
![bildschirmfoto 2014-07-30 um 15 27 02](https://cloud.githubusercontent.com/assets/688980/3749550/3a2e17fe-17ed-11e4-8660-2679c2f95865.png)

**Comment by mattfullerton** [comment]
Ich hatte vorhin gemerkt, dass die Daten als XML verfügbar sind, aber nur zwecks Flash-Visualisierung. Ich bezweifele, dass die Daten im besonderen nutzbaren Format sind bzw. dass die Daten dieses Jahr dann gleich aussehen.

**Comment by milafrerichs** [comment]
Danke @mattfullerton hast du nen Link?
@ClaudiaSchwegmann 
Ich wollte noch mal nachfragen. Willst du die Scores au den Unterseiten? Also für Sicherheit, oder willst du auf der Übersicht in die Balken auch die detaillierten Scores? 
Also wie hier?
![detailiert](https://cloud.githubusercontent.com/assets/688980/3754627/b8963192-181c-11e4-9051-5eb993777a16.png)
Oder reicht dir das wie es jetzt ist? Die detaillierten würden schon recht viel mehr Arbeit bedeuten und ich finde das Format nicht wirklich gut gelöst.

**Comment by mattfullerton** [comment]
http://www.cgdev.org/flash/cdi2013/data_111513.xml
