### ISSUE TITLE
Kachelbereich (1+2 Ebene) nicht in der vollen Breite

### ISSUE THREAD

**Issue by ClaudiaSchwegmann** [okfde/entwicklungsbarometer#38]

**Comment by ClaudiaSchwegmann** [comment]
Der NGO Berein in der dritten Ebene sollte dann auch nicht in der vollen Breite sein.

**Comment by milafrerichs** [comment]
![bildschirmfoto 2014-09-11 um 09 10 27](https://cloud.githubusercontent.com/assets/688980/4237361/2c7a4594-39ce-11e4-8cbd-8936c81343d1.png)

**Comment by milafrerichs** [comment]
![bildschirmfoto 2014-09-11 um 21 22 08](https://cloud.githubusercontent.com/assets/688980/4245297/704049e8-3a34-11e4-90bf-794b4cc824d8.png)
