### ISSUE TITLE
Anteil Waffenhandel am deutschen GDP

### ISSUE THREAD

**Issue by milafrerichs** [okfde/entwicklungsbarometer#63]
> Punktediagramm mit 1000 Punkten für 2011, 2010 und 2009?

**Comment by milafrerichs** [comment]
![bildschirmfoto 2014-12-14 um 14 25 51](https://cloud.githubusercontent.com/assets/688980/5427452/46d95132-839d-11e4-971a-6c71e1f10fac.png)

**Comment by ClaudiaSchwegmann** [comment]
Ja, genau! Gefällt mir sehr gut!!! Allerdings wirkt das Rot doch sehr stark und die Bedeutung von Waffenhandel wirkt doch recht groß. Ich frage mich, ob man ein bißchen mehr whitespace zwischen den Punkten haben könnte. Könntest Du das mal ausprobieren? Eine zweite Idee ist, dass man von die "schädlichen" Waffenexporte in dem Rot lässt und für die übrigen Waffenexporte Punkte mit etwas schwacherem Rot oder nur mit einem roten Rand nimmt. Wir haben ja die Zahlen über den Anteil der Waffenexporte in nicht-freie Länder, in halb-freie Länder und in freie Länder.

**Comment by milafrerichs** [comment]
![bildschirmfoto 2014-12-15 um 18 18 19](https://cloud.githubusercontent.com/assets/688980/5440205/cc29362e-8486-11e4-8be2-21d958926b12.png)

**Comment by ClaudiaSchwegmann** [comment]
Ja, finde ich besser! Danke!
