### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by milafrerichs** [okfde/entwicklungsbarometer#9]
Was für Einträge sollen in der Navigation enthalten sein.
Im Wireframe sind das aktuell:
- About
- Contact
- Share

Ich würde vorschlagen, dass auch die Indikatoren mit aufgenommen werden, als Dropdown:
![entwicklungsbarometer_-_sicherheit](https://cloud.githubusercontent.com/assets/688980/3747104/16da6d48-17ca-11e4-92af-c12d48b8e992.png)

**Comment by ClaudiaSchwegmann** [comment]
Ja, finde ich gut!

**Comment by milafrerichs** [comment]
- [x] Indikatoren
- [x] Experten
- [ ] Über das Projekt
- [x] Kontakt
